/* Auto-generated by genmsg_cpp for file /home/ghaessig/fuerte_workspace/sandbox/differential_drive/msg/Odometry.msg */
#ifndef DIFFERENTIAL_DRIVE_MESSAGE_ODOMETRY_H
#define DIFFERENTIAL_DRIVE_MESSAGE_ODOMETRY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace differential_drive
{
template <class ContainerAllocator>
struct Odometry_ {
  typedef Odometry_<ContainerAllocator> Type;

  Odometry_()
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  Odometry_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _theta_type;
  float theta;


  typedef boost::shared_ptr< ::differential_drive::Odometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::Odometry_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Odometry
typedef  ::differential_drive::Odometry_<std::allocator<void> > Odometry;

typedef boost::shared_ptr< ::differential_drive::Odometry> OdometryPtr;
typedef boost::shared_ptr< ::differential_drive::Odometry const> OdometryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::differential_drive::Odometry_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::differential_drive::Odometry_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace differential_drive

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Odometry_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Odometry_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::Odometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const  ::differential_drive::Odometry_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa130bc60ee651385ULL;
  static const uint64_t static_value2 = 0x5dc62ea83fcc5b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::Odometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "differential_drive/Odometry";
  }

  static const char* value(const  ::differential_drive::Odometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::Odometry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
float32 theta\n\
\n\
";
  }

  static const char* value(const  ::differential_drive::Odometry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::differential_drive::Odometry_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::differential_drive::Odometry_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.theta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Odometry_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::Odometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::differential_drive::Odometry_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_ODOMETRY_H

