/* Auto-generated by genmsg_cpp for file /home/ghaessig/fuerte_workspace/sandbox/differential_drive/msg/Param.msg */
#ifndef DIFFERENTIAL_DRIVE_MESSAGE_PARAM_H
#define DIFFERENTIAL_DRIVE_MESSAGE_PARAM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace differential_drive
{
template <class ContainerAllocator>
struct Param_ {
  typedef Param_<ContainerAllocator> Type;

  Param_()
  : k(0.0)
  , ki(0.0)
  , int_max(0.0)
  {
  }

  Param_(const ContainerAllocator& _alloc)
  : k(0.0)
  , ki(0.0)
  , int_max(0.0)
  {
  }

  typedef float _k_type;
  float k;

  typedef float _ki_type;
  float ki;

  typedef float _int_max_type;
  float int_max;


  typedef boost::shared_ptr< ::differential_drive::Param_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::Param_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Param
typedef  ::differential_drive::Param_<std::allocator<void> > Param;

typedef boost::shared_ptr< ::differential_drive::Param> ParamPtr;
typedef boost::shared_ptr< ::differential_drive::Param const> ParamConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::differential_drive::Param_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::differential_drive::Param_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace differential_drive

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Param_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Param_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::Param_<ContainerAllocator> > {
  static const char* value() 
  {
    return "583e9b7129e1eeaaa3a32940d81f7e97";
  }

  static const char* value(const  ::differential_drive::Param_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x583e9b7129e1eeaaULL;
  static const uint64_t static_value2 = 0xa3a32940d81f7e97ULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::Param_<ContainerAllocator> > {
  static const char* value() 
  {
    return "differential_drive/Param";
  }

  static const char* value(const  ::differential_drive::Param_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::Param_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 k\n\
float32 ki\n\
float32 int_max\n\
\n\
";
  }

  static const char* value(const  ::differential_drive::Param_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::differential_drive::Param_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::differential_drive::Param_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.k);
    stream.next(m.ki);
    stream.next(m.int_max);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Param_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::Param_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::differential_drive::Param_<ContainerAllocator> & v) 
  {
    s << indent << "k: ";
    Printer<float>::stream(s, indent + "  ", v.k);
    s << indent << "ki: ";
    Printer<float>::stream(s, indent + "  ", v.ki);
    s << indent << "int_max: ";
    Printer<float>::stream(s, indent + "  ", v.int_max);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_PARAM_H

