/* Auto-generated by genmsg_cpp for file /home/ghaessig/fuerte_workspace/sandbox/differential_drive/msg/Servomotors.msg */
#ifndef DIFFERENTIAL_DRIVE_MESSAGE_SERVOMOTORS_H
#define DIFFERENTIAL_DRIVE_MESSAGE_SERVOMOTORS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace differential_drive
{
template <class ContainerAllocator>
struct Servomotors_ {
  typedef Servomotors_<ContainerAllocator> Type;

  Servomotors_()
  : servo1(0)
  , servoangle()
  {
    servoangle.assign(0);
  }

  Servomotors_(const ContainerAllocator& _alloc)
  : servo1(0)
  , servoangle()
  {
    servoangle.assign(0);
  }

  typedef uint8_t _servo1_type;
  uint8_t servo1;

  typedef boost::array<uint8_t, 8>  _servoangle_type;
  boost::array<uint8_t, 8>  servoangle;


  typedef boost::shared_ptr< ::differential_drive::Servomotors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::Servomotors_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Servomotors
typedef  ::differential_drive::Servomotors_<std::allocator<void> > Servomotors;

typedef boost::shared_ptr< ::differential_drive::Servomotors> ServomotorsPtr;
typedef boost::shared_ptr< ::differential_drive::Servomotors const> ServomotorsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::differential_drive::Servomotors_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::differential_drive::Servomotors_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace differential_drive

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Servomotors_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Servomotors_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::Servomotors_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f51d948c20e299a516b60c1bba9b447f";
  }

  static const char* value(const  ::differential_drive::Servomotors_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf51d948c20e299a5ULL;
  static const uint64_t static_value2 = 0x16b60c1bba9b447fULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::Servomotors_<ContainerAllocator> > {
  static const char* value() 
  {
    return "differential_drive/Servomotors";
  }

  static const char* value(const  ::differential_drive::Servomotors_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::Servomotors_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# desired angular position\n\
# range 0-180 degrees\n\
\n\
uint8 servo1\n\
uint8[8] servoangle\n\
\n\
";
  }

  static const char* value(const  ::differential_drive::Servomotors_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::differential_drive::Servomotors_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::differential_drive::Servomotors_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.servo1);
    stream.next(m.servoangle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Servomotors_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::Servomotors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::differential_drive::Servomotors_<ContainerAllocator> & v) 
  {
    s << indent << "servo1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servo1);
    s << indent << "servoangle[]" << std::endl;
    for (size_t i = 0; i < v.servoangle.size(); ++i)
    {
      s << indent << "  servoangle[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.servoangle[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_SERVOMOTORS_H

