/* Auto-generated by genmsg_cpp for file /home/ghaessig/fuerte_workspace/sandbox/differential_drive/msg/Size.msg */
#ifndef DIFFERENTIAL_DRIVE_MESSAGE_SIZE_H
#define DIFFERENTIAL_DRIVE_MESSAGE_SIZE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace differential_drive
{
template <class ContainerAllocator>
struct Size_ {
  typedef Size_<ContainerAllocator> Type;

  Size_()
  : r(0.0)
  , b(0.0)
  {
  }

  Size_(const ContainerAllocator& _alloc)
  : r(0.0)
  , b(0.0)
  {
  }

  typedef float _r_type;
  float r;

  typedef float _b_type;
  float b;


  typedef boost::shared_ptr< ::differential_drive::Size_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::Size_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Size
typedef  ::differential_drive::Size_<std::allocator<void> > Size;

typedef boost::shared_ptr< ::differential_drive::Size> SizePtr;
typedef boost::shared_ptr< ::differential_drive::Size const> SizeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::differential_drive::Size_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::differential_drive::Size_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace differential_drive

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Size_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Size_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::Size_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e3a98497364ff6bb0499d0c2310cde71";
  }

  static const char* value(const  ::differential_drive::Size_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe3a98497364ff6bbULL;
  static const uint64_t static_value2 = 0x0499d0c2310cde71ULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::Size_<ContainerAllocator> > {
  static const char* value() 
  {
    return "differential_drive/Size";
  }

  static const char* value(const  ::differential_drive::Size_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::Size_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 r\n\
float32 b\n\
\n\
";
  }

  static const char* value(const  ::differential_drive::Size_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::differential_drive::Size_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::differential_drive::Size_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.r);
    stream.next(m.b);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Size_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::Size_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::differential_drive::Size_<ContainerAllocator> & v) 
  {
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_SIZE_H

