/* Auto-generated by genmsg_cpp for file /home/ghaessig/fuerte_workspace/sandbox/differential_drive/msg/Speed.msg */
#ifndef DIFFERENTIAL_DRIVE_MESSAGE_SPEED_H
#define DIFFERENTIAL_DRIVE_MESSAGE_SPEED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace differential_drive
{
template <class ContainerAllocator>
struct Speed_ {
  typedef Speed_<ContainerAllocator> Type;

  Speed_()
  : header()
  , W1(0.0)
  , W2(0.0)
  {
  }

  Speed_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , W1(0.0)
  , W2(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _W1_type;
  float W1;

  typedef float _W2_type;
  float W2;


  typedef boost::shared_ptr< ::differential_drive::Speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::Speed_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Speed
typedef  ::differential_drive::Speed_<std::allocator<void> > Speed;

typedef boost::shared_ptr< ::differential_drive::Speed> SpeedPtr;
typedef boost::shared_ptr< ::differential_drive::Speed const> SpeedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::differential_drive::Speed_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::differential_drive::Speed_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace differential_drive

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Speed_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::differential_drive::Speed_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::Speed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ae0c4a7348b1a8bfa79b856330d95cad";
  }

  static const char* value(const  ::differential_drive::Speed_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xae0c4a7348b1a8bfULL;
  static const uint64_t static_value2 = 0xa79b856330d95cadULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::Speed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "differential_drive/Speed";
  }

  static const char* value(const  ::differential_drive::Speed_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::Speed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float32 W1\n\
float32 W2\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::differential_drive::Speed_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::differential_drive::Speed_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::differential_drive::Speed_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::differential_drive::Speed_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.W1);
    stream.next(m.W2);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Speed_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::Speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::differential_drive::Speed_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "W1: ";
    Printer<float>::stream(s, indent + "  ", v.W1);
    s << indent << "W2: ";
    Printer<float>::stream(s, indent + "  ", v.W2);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_SPEED_H

