/* Auto-generated by genmsg_cpp for file /home/ghaessig/fuerte_workspace/sandbox/differential_drive/msg/test.msg */
#ifndef DIFFERENTIAL_DRIVE_MESSAGE_TEST_H
#define DIFFERENTIAL_DRIVE_MESSAGE_TEST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace differential_drive
{
template <class ContainerAllocator>
struct test_ {
  typedef test_<ContainerAllocator> Type;

  test_()
  : x(0)
  {
  }

  test_(const ContainerAllocator& _alloc)
  : x(0)
  {
  }

  typedef uint16_t _x_type;
  uint16_t x;


  typedef boost::shared_ptr< ::differential_drive::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::test_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct test
typedef  ::differential_drive::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::differential_drive::test> testPtr;
typedef boost::shared_ptr< ::differential_drive::test const> testConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::differential_drive::test_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::differential_drive::test_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace differential_drive

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::differential_drive::test_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::differential_drive::test_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::test_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e08cf7dfbb235d6fecb1d7d99dab520";
  }

  static const char* value(const  ::differential_drive::test_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e08cf7dfbb235d6ULL;
  static const uint64_t static_value2 = 0xfecb1d7d99dab520ULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::test_<ContainerAllocator> > {
  static const char* value() 
  {
    return "differential_drive/test";
  }

  static const char* value(const  ::differential_drive::test_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::test_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint16 x\n\
\n\
";
  }

  static const char* value(const  ::differential_drive::test_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::differential_drive::test_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::differential_drive::test_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct test_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::differential_drive::test_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_TEST_H

