"""autogenerated by genpy from differential_drive/MouseEvent.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MouseEvent(genpy.Message):
  _md5sum = "ef8c9f3ac43b76bcf800e7d5001209fb"
  _type = "differential_drive/MouseEvent"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 timestamp
int16 dx
int16 dy
uint8 button
uint8 pressed
"""
  __slots__ = ['timestamp','dx','dy','button','pressed']
  _slot_types = ['float64','int16','int16','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,dx,dy,button,pressed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MouseEvent, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.dx is None:
        self.dx = 0
      if self.dy is None:
        self.dy = 0
      if self.button is None:
        self.button = 0
      if self.pressed is None:
        self.pressed = 0
    else:
      self.timestamp = 0.
      self.dx = 0
      self.dy = 0
      self.button = 0
      self.pressed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_d2h2B.pack(_x.timestamp, _x.dx, _x.dy, _x.button, _x.pressed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.timestamp, _x.dx, _x.dy, _x.button, _x.pressed,) = _struct_d2h2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_d2h2B.pack(_x.timestamp, _x.dx, _x.dy, _x.button, _x.pressed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.timestamp, _x.dx, _x.dy, _x.button, _x.pressed,) = _struct_d2h2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d2h2B = struct.Struct("<d2h2B")
